### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by AviFix** [piggydoughnut/node-pdf2img#1]
Hi

Thanks for your work.

I'm trying to use this in an AWS lambda function and I get this error:

    {
       "errorType": "Error",
       "errorMessage": "spawn lambda-ghostscript/bin/./gs ENOENT",
       "trace": [
         "Error: spawn lambda-ghostscript/bin/./gs ENOENT",
         "    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)",
         "    at onErrorNT (internal/child_process.js:415:16)",
         "    at process._tickCallback (internal/process/next_tick.js:63:19)"
       ]
     }

I downloaded the compiled version of Ghostscript from lambda-ghostscript and uploaded it as a was lambda layer and attached the layer to my function.

What else do I need to configure?

How do I set Ghostscript executable to be available in this path lambda-ghostscript/bin/./gs?

Thanks

**Comment by piggydoughnut** [comment]
Hi there 👋🏽  Sorry, I must have missed this. 

I m sure you have already figured it out or went with something else, but just in case. If I were you I would check the name and the path. Do you have ghost script accessible at `lambda-ghostscript/bin/./gs` and also does it have execute permissions  (`chmod +x lambda-ghostscript/bin/./gs`) ?

This is just of the top of my head as I haven't used this for a while.
